<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="pt-10">
    <div class="flex flex-col md:flex-row-reverse md:justify-between md:items-start">
        <div class="pt-4">
            <?= $block->getChildHtml('subscribe') ?>
        </div>

        <div class="pt-4 space-y-4 gap-4 md:space-y-0 md:grid md:grid-cols-3 md:mr-4 ">
            <?= $block->getChildHtml('footer-links-1') ?>
            <?= $block->getChildHtml('footer-links-2') ?>
            <?= $block->getChildHtml('footer-links-3') ?>
        </div>
    </div>


    <div class="flex flex-col-reverse py-4  space-x-2 md:flex-row md:justify-between md:items-center">
        <?= $block->getChildHtml('footer-socials') ?>
        <?= $block->getChildHtml('footer-download') ?>
    </div>
</div>



