<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Theme\Block\Html\Footer;
use Magento\Framework\Escaper;

/** @var Footer $block */
/** @var Escaper $escaper */
?>
<div class="py-4 flex flex-col items-center justify-center space-x-4 md:flex-row">
    <p>
        © 2023
        <a
            href="https://twitter.com/hyva_io"
            target="_blank"
            rel="noopener noreferrer"
            class=" ml-1"
        >Milwaukee Tool Japan.</a>
    </p>

    <p>Unauthorized reproduction is prohibited.</p>
    <p>
        <a href="#">Website of terms</a> |
        <a href="#">Use Privacy Policy</a>
    </p>


    <?php /* Enable the following line to show the copyright information configured in the admin
    <span><?= $escaper->escapeHtml($block->getCopyright()) ?></span>
    */ ?>
</div>
